### ISSUE TITLE
Change upstream / host Owntracks recorder

### ISSUE THREAD

**Issue by CodeShakingSheep** [YunoHost-Apps/owntracks_ynh#33] opened 2024-03-12 14:56 UTC
In `manifest.toml` https://github.com/owntracks/frontend is used as upstream. However, as I understand it this only provides an andvanced interface compared to https://github.com/owntracks/recorder. See `README.me` in https://github.com/owntracks/frontend

> This is a web interface for [OwnTracks](https://github.com/owntracks/recorder) built as a Vue.js single page application. The recorder itself already ships with some basic web pages, this is a more advanced interface with more functionality, all in one place.

So, at the moment this app isn't functional as it doesn't include Owntracks recorder for actually recording location data (e.g. from Android / iOS App). So, there is no location data to be rendered for the frontend. That's why I suggest to either change upstream to Owntracks recorder or include it additionally to the frontend upstream.

**Comment by tituspijean** [comment] 2024-03-16 11:51
Duplicate of #25

**Closed by tituspijean** 2024-03-16 11:51 UTC
